name: conda-env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.12
  - pip
  - ipykernel
  - jupyter
  - mlflow
  - scikit-learn
  - pandas
  - seaborn
  - hyperopt
  - xgboost
  - fastparquet
  - boto3
  - prefect
  - tqdm
  - requests
  - joblib
  - pyarrow
  - psycopg2-binary
  - evidently
  - matplotlib
